<!--
  RECONSTRUCTED FILE — original was lost on 2026-05-26.
  Renders an icon from the SVG sprite generated by vite-plugin-svg-icons.
  Usage: <SvgIcon icon-name="arrow-right-icon" width="16" height="16" />
-->
<template>
  <svg
    :width="width"
    :height="height"
    :class="['svg-icon', `svg-icon--${iconName}`]"
    aria-hidden="true"
    focusable="false"
  >
    <use :href="`#icon-${iconName}`" />
  </svg>
</template>

<script setup lang="ts">
withDefaults(
  defineProps<{
    iconName: string
    width?: string | number
    height?: string | number
  }>(),
  {
    width: '20',
    height: '20',
  },
)
</script>

<style scoped>
.svg-icon {
  display: inline-block;
  vertical-align: middle;
  fill: currentColor;
}
</style>
